title = "Jollof Rice"
category = "Sides"
nationality = "Nigerian"
tags = ["Rice"]
dev = false
site = {nav = false, featured = false}
images = {thumbnail = "chillis_thumb.jpg", banner = "chillis_banner.jpg", gallery = []}
pdf = {layout = "", columns = false, show_image = false}

blurb = ""

ingredients = [
    "2 cups Rice - jasmine or basmati",
    "1 Red pepper",
    "2 Tomatoes",
    "Tomato paste",
    "2 onions",
    "1 Scotch bonnet pepper",
    "4-6 cloves of garlic",
    "Chicken stock",
    "Neutral oil (vegetable/sunflower)",
    "Herbs: thyme, bay leaf",
    "Spices: fennel, clove, ginger, paprika, tumeric",
    "Salt \\& peper",
]

instructions = [
    "Sauce base: blend the red pepper, 1 onion, tomato with some ckicken stock. Fry off and put aside.",
    "Spice blend: In the same pan, fry the remaining onion, garlic, tomato paste, scotch bonnet and spices until fragrant.",
    "Add the rice to the spice mix \\& coat the grains. Add half of the sauce base, stock and water. Add the bay leaves.",
    "Bring to the boil, then simmer on low heat, covered, until rice is cooked (15-20 mins).",
    "Stir through the remaining sauce base, thyme, adjust seasoning and serve.",
]

hints = [
    "Not too much spice or tumeric - Jollof is meant to be red, not orange!",
    "Excess sauce base can be served on the side.",
    "Add oil or butter towards the end of cooking, to prevent the rice becoming dry",
]

[photos]
thumbnail = "photos/general/chillis"
banner = "photos/general/chillis"
gallery = []
