title = "Braised Brisket"
category = "Mains"
tags = []
dev = true
site = {nav = false, featured = false}
images = {thumbnail = "", banner = "", gallery = []}
pdf = {layout = ""}

blurb = "A satisfying winter dish, best cooked low and slow. This is a Jewish-style brisket, rather than Texas smoked brisket. I've found that not all brisket is equal, and ideally you should source a centre-cut flat brisket, with minimal hard fat. Supermarket brisket is often risky, because the shrink-wrapping forces the brisket into a lump, which unravels when you open it. As always, a decent butcher is the safest bet."

ingredients = [
    "1.5kg centre-cut flat brisket",
    "Root vegetables - parsnip, potato",
    "Soffrito or celery",
    "Bay leaves",
    "500ml decent beef stock", 
]

instructions = [
    "In a large oven dish, pour the stock and mix in the soffrito and bay leaves", 
    "Place all other ingredients into the pan - meat in the middle, vegetables round the outside",
    "Wrap in foil, and roast for ~3-4 hours, until the meat is tender.",
    "Once the meat is cooked, take the dish out of the oven. Put the vegetables aside to serve, pour the gravy into a saucepan to thicken",
    "Roast the meat on it's own for 10 minutes in a hot oven, to crisp it up",
]

hints = [
    "You can strain the liquor, and add corn flour to thicken, for a more glossy gravy",
    "You could add mixed spice to the gravy, if you wanted a more distinctive flavour.",
    "Miso is always an easy-win, if the gravy lacks punch."
]
