title = "Vietnamese Summer Rolls"
category = "Mains"
nationality = "Vietnamese"
tags = []
dev = true
site = {nav = false, featured = false}
images = {thumbnail = "", banner = "", gallery = []}
pdf = {layout = ""}

blurb = ""

ingredients = [
    "",
]

instructions = [
    "",
]

hints = [
    "",
]
