title = ""
category = ""
tags = []
dev = false
site = {nav = false, featured = false}
images = {thumbnail = "", banner = "", gallery = []}
pdf = {layout = "", columns = false, show_image = true}

blurb = ""

ingredients = [
    "",
]

instructions = [
    "",
]

hints = [
    "",
]

[photos]
thumbnail = ""
banner = ""
gallery = []
