[defaults]
columns = 1
show_image = true

[[chapters]]
name = "Sauces"
template = "mini"
[chapters.pdf]
recipes = ["chimmichurri", "spicy_vinagrette", "pol_sambol"]

[[chapters]]
name = "Starters"

[chapters.pdf]
recipes = ["pao_de_queijo", "jolloff_rice", "caldo_verde", "feijao"]

[[chapters.recipes]]
id = "pao_de_queijo"
columns = 2     
show_image = true
[chapters.recipes.pdf]

[[chapters.recipes]]
id = "jolloff_rice"
columns = 2
show_image = false

[[chapters]]
name = "Mains"

[chapters.pdf]
recipes = ["cod_with_morcilla", "lamb_shank_curry", "midweek_grilled_chicken copy", "spiced_short_ribs", "puttanesca", "nice_salad", "shakshuka_with_feta"]

[[chapters]]
name = "Special Occaisions"

[chapters.pdf]
recipes = ["christmas_gammon"]