title = "Shakshuka with Feta"
category = "Mains"
nationality = "Middle Eastern"
tags = ["Breakfast"]
dev = false
site = {nav = true, featured = true}
images = {thumbnail = "tomato_thumb.jpg", banner = "tomato_banner.jpg", gallery = []}
pdf = {layout = "", columns = false}

blurb = "This is a great dish, and works for breakfast, lunch or dinner. I like to use the pepper paste and make sure that the bitterness of the peppers balances the sweetness of the tomatoes."

ingredients = [
    "6-8 eggs",
    "100g feta, cubed",
    "2 x 400g tins chopped tomatoes",
    "2 red peppers, deseeded and diced",
    "1 onion, finely diced",
    "4 cloves garlic, sliced",
    "1 tbsp of adjvar (Turkish pepper paste)"
    "1 tbsp of good-quality harissa",
    "Olive oil",
    "Salt & black pepper",
    "Fresh corriander parsley to finish",
]

instructions = [
    "Heat olive oil in a wide, lidded frying pan over medium heat. Fry the onion, garlic and peppers for 8–10 minutes until soft.",
    "Add the harissa and pepper paste. Stir for 1 minute.",
    "Add the tomatoes. Season well. Simmer uncovered for 15 minutes, stirring occasionally, until the sauce thickens.",
    "Add the cubed feta, pushing it below the surface of the sauce."
    "Make wells in the sauce and crack an egg into each one.",
    "Cover with a lid and cook on low heat for 6–8 minutes, until the whites are set but yolks are still runny.",
    "Scatter with parsley and serve immediately, straight from the pan with flatbreads.",
]

hints = [
    "I use the back of a ladle, cracking the egg into the ladle, and rotating to let the egg slide into the depression",
    "Leave the feta in good-sized cubes, so it can stand-up to cooking.",
    "The sauce is fine the next day, but the eggs can be a little rubbery",
]

[photos]
thumbnail = "photos/general/tomato"
banner = "photos/general/tomato"
gallery = []
