title = "Chimichurri"
category = "Sauces"
tags = ["Brazilian"]
dev = false
site = {nav = false, featured = false}
images = {thumbnail = "thumbnail.jpg", banner = "banner.jpg", gallery = ["gallery_1.jpg", "gallery_2.jpg", "gallery_3.jpg", "gallery_4.jpg"]}
pdf = {layout = ""}

blurb = "This is a classic Argentinian sauce, but as it's popular with the ranchers of Rio Grande do Sul, I've considered it Brazilian. This should be intensely flavoured, and the volume can be turned up or down the various consituents according to taste. Personally, I like it moderately spicy, with only a little garlic. The key herb here is oregano, which gives it a distinctive flavour. Always use fresh oregano if you can find it. I am to make ~150ml at a time, and leave it to muddle for a while if you can."

ingredients = [
    "Bunch fresh oregano",
    "Good flat-leaf parsely (not too stalky, dark green)",
    "1 juicy tomato, diced",
    "1 cloves garlic, finely chopped",
    "1 fresh red chilli, finely diced",
    "3 tbsp red wine vinegar",
    "4 tbsp extra virgin olive oil",
    "A good amount of salt & black pepper",
]

instructions = [
    "Finely chop the parsley by hand — don't use a blender or food processor, it turns it into a paste.",
    "Combine parsley, oregano, garlic, and chilli in a bowl.",
    "Stir in the vinegar and olive oil. Season generously.",
]

hints = [
    "Use as a condiment, rather than a marinade.",
    "Avoid too much oil. Balance with more tomato if it's a little dry",
    "I like using mild salad vinegar - not malt or balsamic vinegar. Greek supermarkets often stock a good salad vinegar.",
]
