title = "Palak Paneer"
category = "Mains"
tags = ["Indian", "Vegetarian"]
dev = true
site = {nav = false, featured = false}
images = {thumbnail = "", banner = "", gallery = []}
pdf = {layout = ""}

blurb = ""

ingredients = [
    "",
]

instructions = [
    "",
]

hints = [
    "",
]
