#!/usr/bin/env bash
set -euo pipefail

OUT="pdf/src/chapters/_auto_inputs.tex"
mkdir -p "$(dirname "$OUT")"

echo "% Auto-generated by build/generate_inputs.sh - DO NOT EDIT" > "$OUT"
echo "% Generated on $(date --rfc-3339=seconds 2>/dev/null || date)" >> "$OUT"
echo "" >> "$OUT"

# Find .tex files under pdf/src/chapters, exclude the auto file itself, sort for stable order.
# Use forward slashes and strip the leading "pdf/src/" so \input{chapters/...} works.
find pdf/src/chapters -type f -name '*.tex' ! -name '_auto_inputs.tex' | sort | while read -r f; do
  rel="${f#pdf/src/}"
  printf "%% included: %s\n" "$rel" >> "$OUT"
  printf "\\input{%s}\n\n" "$rel" >> "$OUT"
done

echo "Wrote $OUT"
