# Organized by Category (Google Map Layers)

[Drinks]
"Bohem Tap Room" = "Excellent Czech Pilsner made in London, by actual Czechs. This is the brewery's own tap room."
"Little Green Dragon" = ""
"Mikkeller Brewpub London" = ""
"Nicholas Nickleby" = ""
"Small Beer" = ""
"St John's Tavern" = ""
"The Great Northern Railway Tavern, N8" = ""
"The Sampler" = ""
"The Southampton Arms" = ""
"The Wine Society" = ""

[Eating Out]
"A Portuguese Love Affair Ltd" = ""
"Antepliler Restaurant" = ""
"Balady" = ""
"Bang Bang Oriental Foodhall" = ""
"Beam" = ""
"Clapton Craft" = ""
"Diyarbakir Restaurant" = ""
"Mahavir Sweet Mart" = ""
"Mauritius Paradise" = ""
"Max's Sandwich Shop" = ""
"Monohon Ramen" = ""
"Muay Supermarket" = ""
"Nissi Restaurant" = ""
"Roti King" = ""
"Saffron Kitchen" = ""
"Shrine to the Vine" = ""
"TA’MINI LEBANESE BAKERY" = ""
"The Regency Club" = ""
"The Robin Ale & Cider House" = ""
"The Salt Beef Bar" = ""
"Velasquez and Van Wezel" = ""
"Wing Yip Superstore Cricklewood" = ""

[Supermarkets]
"Astrid Bakery" = ""
"Atariya Foods Finchley" = ""
"Authentique Boulangerie - Whetstone (formerly known as The French Market)" = ""
"Brazilian Centre NORTH FINCHLEY - Produtos Brasileiros (Brazilian Products)" = ""
"Buns From Home" = ""
"Cheeses of Muswell Hill" = ""
"Despina Foods" = ""
"Fortitude Bakehouse" = ""
"GRAHAMS Organic & Free Range" = ""
"Garcia's Foods & Wines of Spain" = ""
"Hops 'N' Pops" = ""
"Kesari Store" = ""
"Margot Bakery" = ""
"Mestizo Mexican Market, Camden" = ""
"Plentiful Foods Indian Spice Ltd" = ""
"Sambal Express Colindale" = ""
"Seabrook butchers" = ""
"Sourdough Sophia - Crouch End" = ""
"Yaşar Halim, Palmers Green" = ""
