[[chapters]]
name = "Starters"
recipes = ["test", "caldo_verde", "feijao", "pao_de_queijo"]

[[chapters.recipe_config]]
id = "test"
image = "test.jpg"

[[chapters]]
name = "Mains"
recipes = []

[[chapters]]
name = "Special Occaisions"
recipes = []

