[[chapters]]
name = "Starters"
recipes = ["caldo_verde", "feijao", "pao_de_queijo"]

[[chapters.recipe_config]]
id = "pao_de_queijo"
tags = ["Brazilian"]
[chapters.recipe_config.images]
thumbnail = "pao_de_queijo.jpg" # Fallback if you haven't made a dedicated thumb yet
banner = "pao_de_queijo_banner.jpg"

[[chapters]]
name = "Mains"
recipes = []

[[chapters]]
name = "Special Occaisions"
recipes = []

[[chapters]]
name = "Sauces"
recipes = ["chimmichurri", "spicy_vinagrette"]

